#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 20 22:33:44 IST 2026
maven-metadata-central.xml.error=Could not transfer metadata org.springframework.boot/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: E\:\\PAFF\\it3030-paf-2026-smart-campus-group26\\.m2-temp\\org\\springframework\\boot\\maven-metadata-central.xml.10711949905413881047.tmp.1683790862700940005.tmp
maven-metadata-central.xml/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1776704624362
