#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jun 05 16:32:57 IST 2026
maven-metadata-central.xml.error=Could not transfer metadata org.jooq/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: F\:\\it3030-paf-2026-smart-campus-group26-main\\.m2-temp\\org\\jooq\\maven-metadata-central.xml.12974398689772315635.tmp.10089751981528559491.tmp
maven-metadata-central.xml/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1780657377757
